Python 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> name="JASWANTH D S"
>>> email="JASDEVSHANKAR@GMAIL.COM"
>>> stack_handle="@Jaswanth"
>>> biostack="GENOMICS,TRANSCRIPTOMICS,DRUG DELIVERY,EPIGENOMICS,MEDICAL CHEMISTRY AND CHEMINFORMATICS,VACINE INFORMATICS"

>>> print("NAME:",name,"EMAIL:",email,"STACK_USERNAME:",stack_handle,"BIOSTACK:",biostack,sep = "\n")
NAME:
JASWANTH D S
EMAIL:
JASDEVSHANKAR@GMAIL.COM
STACK_USERNAME:
@Jaswanth
BIOSTACK:
GENOMICS,TRANSCRIPTOMICS,DRUG DELIVERY,EPIGENOMICS,MEDICAL CHEMISTRY AND CHEMINFORMATICS,VACINE INFORMATICS
>>> 